import { createCurrentIsoDate } from "../../utils/dateFormatters";
import type { PadelitoRepositorySnapshot } from "./padelitoRepository";

export type PadelitoLocalDatabase = PadelitoRepositorySnapshot;

const currentTimestamp = createCurrentIsoDate();

/**
 * Crea la base local inicial del MVP.
 * Se construye para probar flujos sin depender todavia de credenciales Supabase.
 * La usa usePadelitoMvp como estado inicial.
 * Sirve para tener comunidad, seguidores, publicaciones y actividad de ejemplo.
 */
export function createInitialLocalDatabase(): PadelitoLocalDatabase {
  return {
    profiles: [
      {
        profileId: "profile_current_player",
        profileType: "player",
        displayName: "mauriciolaratro",
        avatarUrl: "",
        bio: "Padel en Posadas, partidos tranqui y buena organizacion.",
        whatsappPhone: "5493764000000",
        usualPlace: "Punto Padel",
        matchStatsResetAt: undefined,
        playerLevel: "beginner",
        preferredPosition: "both",
        preferredPlayStyle: "recreational",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        isOnboardingComplete: true,
      },
      {
        profileId: "profile_adria_r",
        profileType: "player",
        displayName: "Adria R.",
        avatarUrl: "",
        bio: "Me sumo a partidos por zona centro.",
        whatsappPhone: "",
        usualPlace: "Centro Posadas",
        matchStatsResetAt: undefined,
        playerLevel: "beginner",
        preferredPosition: "both",
        preferredPlayStyle: "recreational",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        isOnboardingComplete: true,
      },
      {
        profileId: "profile_juani_artigas",
        profileType: "player",
        displayName: "Juani Artigas",
        avatarUrl: "",
        bio: "6ta, busco grupo fijo semanal.",
        whatsappPhone: "",
        usualPlace: "Punto Padel",
        matchStatsResetAt: undefined,
        playerLevel: "sixth",
        preferredPosition: "drive",
        preferredPlayStyle: "competitive",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        isOnboardingComplete: true,
      },
      {
        profileId: "profile_luciana_p",
        profileType: "player",
        displayName: "Luciana P.",
        avatarUrl: "",
        bio: "Juego recreativo, preferentemente tarde/noche.",
        whatsappPhone: "",
        usualPlace: "Club Centro",
        matchStatsResetAt: undefined,
        playerLevel: "seventh",
        preferredPosition: "backhand",
        preferredPlayStyle: "recreational",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        isOnboardingComplete: true,
      },
      {
        profileId: "profile_mati_sosa",
        profileType: "player",
        displayName: "Mati Sosa",
        avatarUrl: "",
        bio: "Competitivo pero sin complicarla.",
        whatsappPhone: "",
        usualPlace: "La Terraza Padel",
        matchStatsResetAt: undefined,
        playerLevel: "sixth",
        preferredPosition: "both",
        preferredPlayStyle: "both",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        isOnboardingComplete: true,
      },
    ],
    follows: [
      {
        followerProfileId: "profile_current_player",
        followedProfileId: "profile_adria_r",
        createdAt: currentTimestamp,
      },
      {
        followerProfileId: "profile_current_player",
        followedProfileId: "profile_juani_artigas",
        createdAt: currentTimestamp,
      },
    ],
    posts: [
      {
        postId: "post_mauricio_punto_padel",
        authorProfileId: "profile_current_player",
        postType: "looking_for_player",
        visibility: "public",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        scheduledDate: "2026-06-26",
        scheduledStartTime: "20:00",
        placeText: "Punto Padel",
        shortNote: "Faltan 4 jugadores principiantes. Posicion indistinta.",
        isActive: true,
        desiredLevel: "beginner",
        desiredPosition: "both",
        desiredPlayStyle: "recreational",
        missingPlayersCount: 4,
        confirmedPlayersText: "mauriciolaratro",
      },
      {
        postId: "post_adria_available_center",
        authorProfileId: "profile_adria_r",
        postType: "available_to_play",
        visibility: "public",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        scheduledDate: "2026-06-23",
        scheduledStartTime: "18:30",
        scheduledEndTime: "22:00",
        placeText: "Zona centro Posadas",
        shortNote: "Busco partido para esta semana en zona centro Posadas.",
        isActive: true,
        availableLevel: "beginner",
        availablePosition: "both",
        availablePlayStyle: "recreational",
        preferredPlaceText: "Centro Posadas",
      },
      {
        postId: "post_juani_fixed_weekly",
        authorProfileId: "profile_juani_artigas",
        postType: "available_to_play",
        visibility: "public",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        scheduledDate: "2026-06-24",
        scheduledStartTime: "20:00",
        scheduledEndTime: "23:00",
        placeText: "Punto Padel",
        shortNote: "Busco partido fijo semanal categoria 6ta.",
        isActive: true,
        availableLevel: "sixth",
        availablePosition: "drive",
        availablePlayStyle: "competitive",
        preferredPlaceText: "Punto Padel",
      },
      {
        postId: "post_luciana_night",
        authorProfileId: "profile_luciana_p",
        postType: "available_to_play",
        visibility: "public",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        scheduledDate: "2026-06-25",
        scheduledStartTime: "19:00",
        scheduledEndTime: "22:00",
        placeText: "Posadas",
        shortNote: "Me sumo a partido recreativo despues de las 19.",
        isActive: true,
        availableLevel: "seventh",
        availablePosition: "backhand",
        availablePlayStyle: "recreational",
        preferredPlaceText: "Posadas",
      },
      {
        postId: "post_mati_weekend",
        authorProfileId: "profile_mati_sosa",
        postType: "available_to_play",
        visibility: "public",
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
        scheduledDate: "2026-06-27",
        scheduledStartTime: "17:00",
        scheduledEndTime: "21:00",
        placeText: "La Terraza Padel",
        shortNote: "Disponible finde para partido 6ta o mixto.",
        isActive: true,
        availableLevel: "sixth",
        availablePosition: "both",
        availablePlayStyle: "both",
        preferredPlaceText: "La Terraza Padel",
      },
    ],
    postInteractions: [],
    matchJoinRequests: [],
    directMatchInvitations: [],
    matchRecords: [],
    matchParticipants: [],
    matchResults: [],
    recurringChallenges: [],
    recurringChallengeParticipants: [],
    notifications: [],
    sessionProfileId: undefined,
    quickAccessPromptDismissed: false,
  };
}
